### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Pattern-Printing-Codes#13]
Create the Fibonacci Series upto n terms in any language of your chice

**Comment by Subhadas2000** [comment]
please assign this to me

**Comment by abirbhattacharya82** [comment]
I have assigned you to this issue continue contributing now

**Comment by MuditJain5** [comment]
Please assign this issue to me

**Comment by rohan26062001** [comment]
I am done, please check

**Comment by sagar-monga** [comment]
PLease Assign this to me in Java

**Comment by shashank1503-cipher** [comment]
Can you assign this to me for python.Would be great to work on

**Comment by shashank1503-cipher** [comment]
Thank you for Assigning! Made a Pull request Regarding it
