### ISSUE TITLE
Pascal-Triangle

### ISSUE THREAD

**Issue by abirbhattacharya82** [abirbhattacharya82/Pattern-Printing-Codes#3]
Any Programming Languages solving this issue is accepted.

**Comment by aniket-24** [comment]
Please assign me this issue under Hacktoberfest!

**Comment by SoumyadeepMukherjee** [comment]
Hello Abir, can you assign me this issue!

**Comment by Subhadas2000** [comment]
please assign this to me

**Comment by abirbhattacharya82** [comment]
I have assigned you with the issue, you can start working in it now

**Comment by SujalSamai** [comment]
Can you please assign me this, I can contribute the Java solution for this. Thank you!
